services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    environment:
      - DOMAIN=$DOMAIN
      - APP_ID=$APP_ID
      - APP_SECRET=$APP_SECRET
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
